### ISSUE TITLE
Go To Wiki/Create Link does not seem to work

### ISSUE THREAD

**Issue by nickbrooking** [hannut91/vs-code-wiki#17]
Nothing I do can make the Go To Wiki/Create Wiki Link command work at all. I tried with the file already existing as well. (vimwiki will create the file if it doesn't already exist.)

Windows 10 x64
VSCode 1.42.1

**Comment by hannut91** [comment]
Currently not working in Window. I only tested it on Mac. I'm sorry. I'll fix it right away and leave an answer tomorrow.

**Comment by hannut91** [comment]
I updated to `0.4.4`.
Open Wiki and GoToWiki is now working and the rest are not currently working.

**Comment by nickbrooking** [comment]
Seems to be working for me now, thanks!
