### ISSUE TITLE
GoToWiki/OpenWiki does not work if number in link

### ISSUE THREAD

**Issue by nickbrooking** [hannut91/vs-code-wiki#19]
If you have a number in the name of a wiki document, it will not navigate there:

This works:
`[TestLink](TestLink.md}`

This does NOT work:
`[Test2Link](Test2Link.md)`

If you try to GoToWiki on the second link there, it attempts to make a link again instead like this:
`[[Test2Link](Test2Link.md)]([Test2Link](Test2Link.md).md)`

Windows x64
VSCode 1.42.1

**Comment by hannut91** [comment]
Thanks to you, I found a bug and fixed it. Thank you.
