### ISSUE TITLE
한글 링크 생성 미 지원 문제

### ISSUE THREAD

**Issue by deadcatssociety** [hannut91/vs-code-wiki#21]
안녕하세요
최근 VimWiki에 대해 알게되서 보다가, Vim 자체를 잘 안써서 VSCode에 비슷한 확장 없나 찾다가 발견하여 반가운 마음에 써보려고 하고 있습니다.

## 이슈:
한글링크 생성은 되나 문서이동+새 파일이 만들어지지 않는 문제

### 설명
한글 단어에서 링크 생성 및 이동을 하면 새 파일이 만들어 지지 않고 링크를 한번 더 생성하는 이슈가 있음

### 예시:
- `한글테스트`
`ctrl+]` 입력 시
- `[한글테스트](한글테스트.md)`
`[한글테스트]`에서 `ctrl+]` 입력 시
- `[[한글테스트](한글테스트.md)]([한글테스트](한글테스트.md).md)`

테스트 환경: MacOS 10.15.3
VSCode 버전: 1.42.1
vs-code-wiki 버전: 0.4.5

확인 부탁드립니다.
감사합니다.

**Comment by hannut91** [comment]
관심 가져주셔서 감사합니다 ㅎㅎ 또한 버그를 발견하게 해주셔서 감사합니다. 수정하고 답변 드리겠습니다.

**Comment by hannut91** [comment]
`0.4.6`버전을 사용하시면 수정된 것을 확인하실 수 있습니다. 마켓에 올라가는데 시간이 좀 걸릴 수 있습니다. 감사합니다.

See also
  - https://github.com/hannut91/vs-code-wiki/pull/23
