### ISSUE TITLE
설정 변경 미적용

### ISSUE THREAD

**Issue by deadcatssociety** [hannut91/vs-code-wiki#22]
## 이슈
Settings - Extensions - VS Code Wiki 에서 설정 변경 후 vscode 재실행 하지 않으면 설정이 적용되지 않는 이슈

### 예시
설치 후 
Settings - Extensions - VS Code Wiki - Wiki: Base Path 변경 후 Open Wiki 선택
-> 기본 경로에 만들어짐
Settings - Extensions - VS Code Wiki - Wiki: Target Path 변경 후 Export Wiki 선택 시
-> 설정된 경로가 없다는 에러 출력

**Comment by hannut91** [comment]
앗.. 알고 있던 건데 제가 수정을 안하고 있었습니다 ㅠ 내일 바로 수정하고 답변 남길게여

**Comment by hannut91** [comment]
수정해서 업로드했습니다. `0.4.7`버전으로 올렸습니다.

**Comment by deadcatssociety** [comment]
0.4.7을 설치하고 경로 지정 후 go to wiki를 했더니 '**Selectd** editor is not exist' 에러가 발생합니다.

**Comment by deadcatssociety** [comment]
그 외 export의 경우 폴더가 지정되어 있지 않으면 생성이 되지 않습니다. 이것도 디폴트 패스가 있는게 좋을 것 같습니다.

**Comment by hannut91** [comment]
export의 경우 지정한 곳으로 export하는 기능이므로 지정되어 있지 않으면 동작하지 않도록 했습니다.
