### ISSUE TITLE
Issues while using in wsl

### ISSUE THREAD

**Issue by aasutossh** [hannut91/vs-code-wiki#35]
Just installed it (was looking for vimwiki alternatives), I mostly use vscode with wsl (2).
Installed it, reloaded vscode. Created new wiki, then when I click the new link inside of wiki error pops, it says 
```
Unable to open 'Django.md': Unable to read file 'vscode-remote://wsl+ubuntu/home/aa/vscode_wiki/Django.md' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu/home/aa/vscode_wiki/Django.md').
```
![image](https://user-images.githubusercontent.com/18498932/88936552-c3384080-d2a2-11ea-9c0a-1877034284dd.png)

**Comment by aasutossh** [comment]
Maybe it's how it is supposed to work, I mean clicking the link should create the file if it doesn't exist.

Clicking the `Create File` button works. If it's not an *issue* feel free to close it.

**Comment by hannut91** [comment]
If you want to create the file, You should to run `Create File` action.
Clicking with the mouse is a feature of the editor.

**Comment by aasutossh** [comment]
> You should to run Create File action.

How?

**Comment by hannut91** [comment]
There is no way to create file when click link. Default short cut is ctrl + ] on mac os.

**Comment by hannut91** [comment]
Sorry not action. Its `Go to Wiki` Command. This is to create link and create file when file is not exist
