### ISSUE TITLE
Broken goToWiki functionality

### ISSUE THREAD

**Issue by tom1700** [hannut91/vs-code-wiki#38]
I'm afraid the `goToWiki` doesn't work anymore.

What I've tried:
1.  On Windows in VS code version 1.49.3
  a) using shortcut ctrl+]
  b) using command goToWiki

2. On OSX in VS code version 1.49.3
  a) using shortcut ctrl+]
  b) using command goToWiki

Generally, nothing happens

**Comment by hannut91** [comment]
I did try on OSX in VS Code version 1.49.3 but It worked fine.
Let me know How it doesn't work.
Have you tried with `Open Wiki`?

**Comment by tom1700** [comment]
Ok, you can close it, I had the whole concept wrong 😅 

I didn't understand that the wiki lives outside of the project and that the commands will only work there.

**Comment by tom1700** [comment]
Works as expected.
